"""
v3 report pipeline: stitches one holding's Kite position, real technical
indicators, screener fundamentals, cached concall summaries and (optionally)
an LLM narrative into a single research note — as structured JSON and as a
rendered Markdown document.

Design:
- build_report_data(...) and render_markdown(...) are pure (offline-testable).
- generate_for_holding()/generate_portfolio_report() are the online
  orchestrators; DB / Kite / yfinance / LLM imports stay lazy so the module
  imports cleanly without any of them configured.
"""
import logging
import os
import re
from datetime import date, datetime
from typing import Dict, List, Optional

from app.services.technicalIndicator_service import TechnicalIndicatorService
from app.services.fundamental_analysis_service import FundamentalAnalysisService
from app.services.scorecard_service import ScorecardService

logger = logging.getLogger(__name__)

REPORTS_DIR = os.path.join(os.getcwd(), "reports")
CONCALL_QUESTION_TITLES = [
    "Business performance highlights",
    "Management commentary & strategic priorities",
    "Future outlook & growth drivers",
    "Risks, challenges & concerns",
    "Financial position & capital allocation",
]
DISCLAIMER = (
    "*Generated by StockAnalyser from portfolio, market, screener and concall "
    "data. All scores and stances are rule-based signals, not investment "
    "advice. Verify figures before acting.*")


def _fmt(value, suffix="", nd="n/a"):
    if value is None:
        return nd
    if isinstance(value, float):
        return f"{value:,.1f}{suffix}"
    return f"{value:,}{suffix}" if isinstance(value, int) else f"{value}{suffix}"


def _concall_key_insights(answer: str, max_lines: int = 6) -> List[str]:
    """Pull the '### Key Insights' bullet lines out of a batch-evaluate answer."""
    lines = []
    in_section = False
    for line in (answer or "").splitlines():
        stripped = line.strip()
        if stripped.startswith("###"):
            in_section = "key insight" in stripped.lower()
            continue
        if in_section and stripped.startswith("-"):
            lines.append(re.sub(r"\*\*", "", stripped))
            if len(lines) >= max_lines:
                break
    return lines


class StockReportService:

    # ------------------------------------------------------------------- build
    @staticmethod
    def build_report_data(holding: Dict,
                          bars: Optional[List[Dict]] = None,
                          scrape_data: Optional[Dict] = None,
                          concall_answers: Optional[List[str]] = None,
                          concall_quarter_date: Optional[date] = None) -> Dict:
        """Pure assembly of every analysis section for one holding."""
        indicators = None
        if bars:
            try:
                indicators = TechnicalIndicatorService.compute_indicators(bars)
            except Exception as e:
                logger.error(f"Indicator computation failed for {holding.get('symbol')}: {e}")

        fundamentals = None
        if scrape_data:
            try:
                fundamentals = FundamentalAnalysisService.analyze(
                    scrape_data, current_price=holding.get("current_price"))
            except Exception as e:
                logger.error(f"Fundamental analysis failed for {holding.get('symbol')}: {e}")

        scorecard = ScorecardService.build(holding, indicators or {}, fundamentals or {})

        concall = None
        if concall_answers:
            concall = {
                "quarter_date": concall_quarter_date,
                "sections": [
                    {"title": CONCALL_QUESTION_TITLES[i] if i < len(CONCALL_QUESTION_TITLES)
                     else f"Question {i + 1}",
                     "key_insights": _concall_key_insights(a),
                     "full_answer": a}
                    for i, a in enumerate(concall_answers)
                ],
            }

        return {
            "symbol": holding.get("symbol"),
            "company_name": holding.get("company_name"),
            "generated_at": datetime.now().isoformat(timespec="seconds"),
            "holding": holding,
            "technicals": indicators,
            "fundamentals": fundamentals,
            "concall": concall,
            "scorecard": scorecard,
            "data_coverage": {
                "price_history": bars is not None and len(bars or []) > 0,
                "screener_fundamentals": scrape_data is not None,
                "concall_summary": bool(concall_answers),
            },
        }

    # ------------------------------------------------------------------ render
    @staticmethod
    def render_markdown(report: Dict, llm_narrative: Optional[str] = None) -> str:
        h = report["holding"]
        ind = report.get("technicals") or {}
        fund = report.get("fundamentals") or {}
        sc = report.get("scorecard") or {}
        growth = fund.get("growth", {})
        quality = fund.get("quality", {})
        sh = fund.get("shareholding", {})
        val = fund.get("valuation", {})
        risk = sc.get("position_risk", {})

        md = []
        md.append(f"# {report['company_name']} ({report['symbol']}) — Research Note")
        md.append(f"*Generated {report['generated_at']}*")
        md.append("")

        # ---- verdict box
        if sc.get("composite_score") is not None:
            md.append(f"**Composite score: {sc['composite_score']}/10 — {sc['stance']}**")
            md.append("")
        if llm_narrative:
            md.append("## Analyst View (AI)")
            md.append("")
            md.append(llm_narrative)
            md.append("")

        # ---- position
        md.append("## Position")
        md.append("")
        md.append("| Metric | Value |")
        md.append("|---|---|")
        md.append(f"| Quantity | {_fmt(h.get('quantity'))} |")
        md.append(f"| Avg. buy price | ₹{_fmt(h.get('average_price'))} |")
        md.append(f"| Current price | ₹{_fmt(h.get('current_price'))} |")
        md.append(f"| Invested / Current value | ₹{_fmt(h.get('invested_value'))} / ₹{_fmt(h.get('current_value'))} |")
        md.append(f"| Unrealized P&L | ₹{_fmt(h.get('profit_loss'))} ({_fmt(h.get('profit_loss_percent'), '%')}) |")
        md.append(f"| Portfolio concentration | {_fmt(h.get('portfolio_concentration'), '%')} |")
        md.append("")

        # ---- scorecard
        pillars = sc.get("pillar_scores", {})
        if any(v is not None for v in pillars.values()):
            md.append("## Scorecard")
            md.append("")
            md.append("| Pillar | Score (0-10) | Weight |")
            md.append("|---|---|---|")
            for k in ("growth", "quality", "technicals", "valuation"):
                md.append(f"| {k.title()} | {_fmt(pillars.get(k))} | {int(sc['weights'][k] * 100)}% |")
            md.append(f"| **Composite** | **{_fmt(sc.get('composite_score'))}** | |")
            md.append("")

        # ---- technicals
        if ind:
            md.append("## Technical Setup")
            md.append("")
            md.append("| Indicator | Value | Read |")
            md.append("|---|---|---|")
            md.append(f"| Last close | ₹{_fmt(ind.get('last_close'))} | |")
            trend = "price above" if (ind.get('price_vs_dma200_percent') or 0) > 0 else "price below"
            md.append(f"| 50 / 200 DMA | ₹{_fmt(ind.get('dma_50'))} / ₹{_fmt(ind.get('dma_200'))} "
                      f"| {str(ind.get('dma_crossover') or '').replace('_', ' ')}, {trend} 200-DMA |")
            md.append(f"| MACD vs signal | {_fmt(ind.get('macd'))} vs {_fmt(ind.get('macd_signal'))} "
                      f"| {ind.get('macd_trend') or 'n/a'} |")
            md.append(f"| RSI (14) | {_fmt(ind.get('rsi_14'))} | "
                      f"{'overbought' if (ind.get('rsi_14') or 50) >= 70 else 'oversold' if (ind.get('rsi_14') or 50) <= 30 else 'neutral zone'} |")
            md.append(f"| 52-week range | ₹{_fmt(ind.get('low_52w'))} – ₹{_fmt(ind.get('high_52w'))} "
                      f"| {_fmt(ind.get('percent_from_52w_high'), '%')} from high |")
            md.append(f"| Support / Resistance | ₹{_fmt(ind.get('support'))} / ₹{_fmt(ind.get('resistance'))} | swing levels |")
            md.append(f"| ATR (14) | {_fmt(ind.get('atr_14'))} ({_fmt(ind.get('atr_percent'), '%')}) | daily range |")
            md.append(f"| Volatility (1y) | {_fmt(ind.get('annualized_volatility_percent'), '%')} "
                      f"| max drawdown {_fmt(ind.get('max_drawdown_percent'), '%')} |")
            md.append("")

        # ---- fundamentals
        if fund:
            md.append("## Fundamentals")
            md.append("")
            md.append("### Growth")
            md.append("")
            md.append("| Metric | Value |")
            md.append("|---|---|")
            md.append(f"| Sales (TTM) | ₹{_fmt(growth.get('sales_ttm'))} Cr ({_fmt(growth.get('sales_ttm_growth_percent'), '%')} YoY) |")
            md.append(f"| Net profit (TTM) | ₹{_fmt(growth.get('net_profit_ttm'))} Cr ({_fmt(growth.get('net_profit_ttm_growth_percent'), '%')} YoY) |")
            md.append(f"| Latest quarter YoY | sales {_fmt(growth.get('latest_quarter_sales_yoy_percent'), '%')}, "
                      f"profit {_fmt(growth.get('latest_quarter_np_yoy_percent'), '%')} |")
            md.append(f"| Sales CAGR 3y / 5y | {_fmt(growth.get('sales_cagr_3y'), '%')} / {_fmt(growth.get('sales_cagr_5y'), '%')} |")
            md.append(f"| Profit CAGR 3y / 5y | {_fmt(growth.get('profit_cagr_3y'), '%')} / {_fmt(growth.get('profit_cagr_5y'), '%')} |")
            md.append("")
            md.append("### Quality")
            md.append("")
            md.append("| Metric | Value |")
            md.append("|---|---|")
            md.append(f"| OPM (last 4q avg) | {_fmt(quality.get('opm_recent_4q_percent'), '%')} "
                      f"({_fmt(quality.get('opm_trend_pp'), 'pp')} vs prior 4q) |")
            md.append(f"| ROCE | {_fmt(quality.get('roce_latest_percent'), '%')} "
                      f"(3y ago: {_fmt(quality.get('roce_3y_ago_percent'), '%')}) |")
            md.append(f"| CFO / PAT | {_fmt(quality.get('cfo_to_pat_percent'), '%')} |")
            md.append(f"| Free cash flow (latest FY) | ₹{_fmt(quality.get('free_cash_flow_latest'))} Cr |")
            md.append(f"| Debt / Equity | {_fmt(quality.get('debt_to_equity'))} |")
            md.append(f"| Cash conversion cycle | {_fmt(quality.get('cash_conversion_cycle_latest'))} days "
                      f"(3y ago: {_fmt(quality.get('cash_conversion_cycle_3y_ago'))}) |")
            md.append(f"| Dividend payout | {_fmt(quality.get('dividend_payout_latest_percent'), '%')} |")
            md.append("")
            md.append("### Shareholding")
            md.append("")
            md.append("| Holder | Latest | Change (4q) |")
            md.append("|---|---|---|")
            md.append(f"| Promoters | {_fmt(sh.get('promoter_latest_percent'), '%')} | {_fmt(sh.get('promoter_change_4q_pp'), 'pp')} |")
            md.append(f"| FIIs | {_fmt(sh.get('fii_latest_percent'), '%')} | {_fmt(sh.get('fii_change_4q_pp'), 'pp')} "
                      f"(window: {_fmt(sh.get('fii_change_full_window_pp'), 'pp')}) |")
            md.append(f"| DIIs | {_fmt(sh.get('dii_latest_percent'), '%')} | {_fmt(sh.get('dii_change_4q_pp'), 'pp')} |")
            md.append(f"| Public | {_fmt(sh.get('public_latest_percent'), '%')} | |")
            md.append("")
            md.append("### Valuation")
            md.append("")
            md.append("| Metric | Value |")
            md.append("|---|---|")
            md.append(f"| EPS (TTM) | ₹{_fmt(val.get('eps_ttm'))} |")
            md.append(f"| P/E (TTM) | {_fmt(val.get('pe_ttm'))}x |")
            md.append(f"| Earnings yield | {_fmt(val.get('earnings_yield_percent'), '%')} |")
            md.append(f"| PEG (vs {_fmt(val.get('growth_used_for_peg_percent'), '%')} growth) | {_fmt(val.get('peg'))} |")
            md.append("")

            if fund.get("positives"):
                md.append("### Positives")
                md.append("")
                for p in fund["positives"]:
                    md.append(f"- {p}")
                md.append("")
            if fund.get("red_flags"):
                md.append("### Red Flags")
                md.append("")
                for r in fund["red_flags"]:
                    md.append(f"- ⚠️ {r}")
                md.append("")

        # ---- concall
        concall = report.get("concall")
        if concall:
            qd = concall.get("quarter_date")
            md.append(f"## Latest Concall Insights{f' (quarter ending {qd})' if qd else ''}")
            md.append("")
            for section in concall["sections"]:
                insights = section["key_insights"]
                if insights:
                    md.append(f"### {section['title']}")
                    md.append("")
                    md.extend(insights)
                    md.append("")

        # ---- risk & triggers
        if risk.get("notes"):
            md.append("## Position Risk")
            md.append("")
            for n in risk["notes"]:
                md.append(f"- {n}")
            md.append("")
        if sc.get("watch_triggers"):
            md.append("## Watch Triggers")
            md.append("")
            for t in sc["watch_triggers"]:
                md.append(f"- {t}")
            md.append("")

        md.append("---")
        md.append(DISCLAIMER)
        return "\n".join(md)

    # -------------------------------------------------------- portfolio rollup
    @staticmethod
    def render_portfolio_markdown(totals: Dict, reports: List[Dict],
                                  not_tracked: List[str],
                                  overall_narrative: Optional[str] = None) -> str:
        md = [f"# Portfolio Intelligence Report",
              f"*Generated {datetime.now().isoformat(timespec='seconds')}*", ""]
        md.append("| Metric | Value |")
        md.append("|---|---|")
        md.append(f"| Portfolio value | ₹{_fmt(totals.get('portfolio_value'))} |")
        md.append(f"| Total invested | ₹{_fmt(totals.get('total_investment'))} |")
        md.append(f"| Total P&L | ₹{_fmt(totals.get('total_pnl'))} ({_fmt(totals.get('total_pnl_percent'), '%')}) |")
        md.append("")

        if overall_narrative:
            md.append("## Overall View (AI)")
            md.append("")
            md.append(overall_narrative)
            md.append("")

        md.append("## Holdings Scorecard")
        md.append("")
        md.append("| Symbol | Value | P&L % | Weight % | Composite | Stance |")
        md.append("|---|---|---|---|---|---|")
        for r in sorted(reports, key=lambda x: -(x["holding"].get("current_value") or 0)):
            h, sc = r["holding"], r.get("scorecard", {})
            md.append(f"| {r['symbol']} | ₹{_fmt(h.get('current_value'))} "
                      f"| {_fmt(h.get('profit_loss_percent'), '%')} "
                      f"| {_fmt(h.get('portfolio_concentration'), '%')} "
                      f"| {_fmt(sc.get('composite_score'))} | {sc.get('stance') or 'n/a'} |")
        md.append("")

        # concentration
        weights = sorted((r["holding"].get("portfolio_concentration") or 0 for r in reports),
                         reverse=True)
        top3 = round(sum(weights[:3]), 1) if weights else None
        hhi = round(sum(w * w for w in weights), 0) if weights else None
        md.append("## Concentration")
        md.append("")
        md.append(f"- Top-3 holdings weight: **{_fmt(top3, '%')}**")
        md.append(f"- Herfindahl index (sum of squared weights): {_fmt(hhi)} "
                  f"({'concentrated' if (hhi or 0) > 1500 else 'reasonably diversified'})")
        overweight = [r["symbol"] for r in reports
                      if (r["holding"].get("portfolio_concentration") or 0) >= 10]
        if overweight:
            md.append(f"- Holdings ≥10% of portfolio: {', '.join(overweight)}")
        md.append("")

        # flags across portfolio
        flagged = [(r["symbol"], f) for r in reports
                   for f in ((r.get("fundamentals") or {}).get("red_flags") or [])]
        if flagged:
            md.append("## Red Flags Across Holdings")
            md.append("")
            for sym, f in flagged:
                md.append(f"- **{sym}**: {f}")
            md.append("")
        if not_tracked:
            md.append(f"*Not analysed (missing from stocks table): {', '.join(not_tracked)}*")
            md.append("")
        md.append("---")
        md.append(DISCLAIMER)
        return "\n".join(md)

    # --------------------------------------------------------------- LLM layer
    @staticmethod
    def _llm_narrative(report: Dict) -> Optional[str]:
        """Optional DeepSeek-written analyst paragraph; returns None on any failure."""
        try:
            from app.agenticAI.llm_Model import LLMFactory
            llm = LLMFactory.get_deepseek(metadata={"endpoint": "portfolio_report"})

            sc = report.get("scorecard", {})
            concall_bullets = []
            for s in ((report.get("concall") or {}).get("sections") or [])[:3]:
                concall_bullets.extend(s["key_insights"][:3])

            prompt = f"""You are an equity analyst. Write a 4-6 sentence view of this holding.

Stock: {report['company_name']} ({report['symbol']})
Position: {report['holding'].get('portfolio_concentration')}% of portfolio, unrealized P&L {report['holding'].get('profit_loss_percent')}%.
Pillar scores (0-10): {sc.get('pillar_scores')}
Composite: {sc.get('composite_score')} — {sc.get('stance')}
Red flags: {(report.get('fundamentals') or {}).get('red_flags')}
Positives: {(report.get('fundamentals') or {}).get('positives')}
Key concall takeaways: {concall_bullets}

Cover: business momentum, technical setup, valuation tension, and the single most important thing to watch. Plain text, no headers, no disclaimers."""
            result = llm.invoke(prompt)
            return result.content.strip()
        except Exception as e:
            logger.warning(f"LLM narrative unavailable for {report.get('symbol')}: {e}")
            return None

    @staticmethod
    def _llm_overall(totals: Dict, reports: List[Dict]) -> Optional[str]:
        try:
            from app.agenticAI.llm_Model import LLMFactory
            llm = LLMFactory.get_deepseek(metadata={"endpoint": "portfolio_report_overall"})
            lines = [
                f"- {r['symbol']}: weight {r['holding'].get('portfolio_concentration')}%, "
                f"P&L {r['holding'].get('profit_loss_percent')}%, "
                f"composite {r.get('scorecard', {}).get('composite_score')} "
                f"({r.get('scorecard', {}).get('stance')})"
                for r in reports]
            prompt = f"""You are an equity analyst reviewing a personal portfolio.
Value {totals.get('portfolio_value')}, P&L {totals.get('total_pnl_percent')}%.
Holdings:
{chr(10).join(lines)}

Write 5-7 sentences: overall health, concentration risk, strongest and weakest holdings, and what to prioritise next quarter. Plain text."""
            return llm.invoke(prompt).content.strip()
        except Exception as e:
            logger.warning(f"LLM overall narrative unavailable: {e}")
            return None

    # ----------------------------------------------------------------- online
    @staticmethod
    def _get_stock_context(symbol: str):
        """(scrape_data_dict, concall_answers, concall_quarter_date) from DB, all optional."""
        from app.database.connection import DatabaseConnection
        from app.database.stock_repository import StockRepository
        from app.database.summary_repository import SummaryRepository
        from app.database.stock_scrap_data_repository import StockScrapeDataRepository

        if not DatabaseConnection.is_enabled():
            return None, None, None
        session = DatabaseConnection.get_session()
        if not session:
            return None, None, None
        try:
            stock = StockRepository.get_by_ticker(session, symbol)
            if not stock:
                return None, None, None

            scrape = StockScrapeDataRepository.get_latest_by_stock_id(session, stock.id)
            scrape_data = None
            if scrape:
                scrape_data = {
                    "quarters": scrape.quarter_result,
                    "profit-loss": scrape.profit_loss,
                    "shareholding": scrape.shareholding_pattern,
                }
                # balance-sheet / cash-flow / ratios are not persisted in
                # stock_scrape_data yet; fundamentals degrade gracefully.

            answers, quarter_date = None, None
            summaries = SummaryRepository.get_by_stock_id(session, stock.id, limit=1)
            if summaries:
                s = summaries[0]
                answers = [a for a in [s.answer1, s.answer2, s.answer3, s.answer4, s.answer5] if a]
                quarter_date = s.quarter_date
            return scrape_data, answers or None, quarter_date
        finally:
            session.close()

    @staticmethod
    def _fetch_bars(symbol: str, exchange: str, period: str) -> Optional[List[Dict]]:
        from app.services.market_data_service import MarketDataService
        suffix = ".NS" if (exchange or "NSE").upper() == "NSE" else ".BO"
        history = MarketDataService.get_history(f"{symbol.upper()}{suffix}",
                                                period=period, interval="1d")
        return history.get("bars") if history else None

    @staticmethod
    def _save_markdown(name: str, content: str) -> str:
        os.makedirs(REPORTS_DIR, exist_ok=True)
        path = os.path.join(REPORTS_DIR, f"{name}_{date.today().isoformat()}.md")
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return path

    @staticmethod
    def generate_for_holding(holding: Dict, period: str = "1y",
                             use_llm: bool = False, save: bool = True) -> Dict:
        symbol = holding["symbol"]
        bars = None
        try:
            bars = StockReportService._fetch_bars(symbol, holding.get("exchange", "NSE"), period)
        except Exception as e:
            logger.warning(f"Price history fetch failed for {symbol}: {e}")

        scrape_data, answers, quarter_date = None, None, None
        try:
            scrape_data, answers, quarter_date = StockReportService._get_stock_context(symbol)
        except Exception as e:
            logger.warning(f"DB context unavailable for {symbol}: {e}")

        report = StockReportService.build_report_data(
            holding, bars=bars, scrape_data=scrape_data,
            concall_answers=answers, concall_quarter_date=quarter_date)

        narrative = StockReportService._llm_narrative(report) if use_llm else None
        report["llm_narrative"] = narrative
        markdown = StockReportService.render_markdown(report, llm_narrative=narrative)
        report["markdown"] = markdown
        if save:
            report["markdown_path"] = StockReportService._save_markdown(symbol, markdown)
        return report

    @staticmethod
    def generate_portfolio_report(period: str = "1y", use_llm: bool = False,
                                  save: bool = True) -> Dict:
        from app.services.kite_service import KiteService

        portfolio = KiteService().get_portfolio()
        totals = {k: portfolio[k] for k in
                  ("portfolio_value", "total_investment", "total_pnl", "total_pnl_percent")}

        reports, not_tracked = [], []
        for holding in portfolio["holdings"]:
            try:
                r = StockReportService.generate_for_holding(
                    holding, period=period, use_llm=use_llm, save=save)
                if not r["data_coverage"]["screener_fundamentals"] \
                        and not r["data_coverage"]["concall_summary"]:
                    not_tracked.append(holding["symbol"])
                reports.append(r)
            except Exception as e:
                logger.error(f"Report generation failed for {holding['symbol']}: {e}")
                not_tracked.append(holding["symbol"])

        overall = StockReportService._llm_overall(totals, reports) if use_llm else None
        rollup_md = StockReportService.render_portfolio_markdown(
            totals, reports, not_tracked, overall_narrative=overall)

        result = {
            **totals,
            "overall_narrative": overall,
            "reports": reports,
            "not_tracked": sorted(set(not_tracked)),
            "rollup_markdown": rollup_md,
        }
        if save:
            result["rollup_markdown_path"] = StockReportService._save_markdown(
                "PORTFOLIO", rollup_md)
        return result
